apiVersion: apps/v1
kind: Deployment
metadata:
  name: habit-tracker
  namespace: habit-tracker
spec:
  replicas: 2 # Running 2 copies for reliability
  selector:
    matchLabels:
      app: habit-tracker
  template:
    metadata:
      labels:
        app: habit-tracker
    spec:
      containers:
      - name: habit-app
        image: gorkememir/habit-tracker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: habit-service
  namespace: habit-tracker
spec:
  type: NodePort
  selector:
    app: habit-tracker
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007 # Access via http://<SERVER_IP>:30007